services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: badminton-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: badminton
      POSTGRES_USER: badminton
      POSTGRES_PASSWORD: badminton_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: