"""add embedding to rackets

Revision ID: a217395cc2db
Revises: 1501caa3a0ef
Create Date: 2026-08-06 19:10:31.109455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a217395cc2db'
down_revision: Union[str, Sequence[str], None] = '1501caa3a0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rackets', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rackets', 'embedding')
    # ### end Alembic commands ###
